dataset:
    data_dir: '/data/anitha/label_free/image_tile_256-256_step_256-256'
    input_channels: [3]
    target_channels: [0]
    split_by_column: pos_idx
    split_ratio:
        train: 0.7
        val: 0.15
        test: 0.15
    height: 256
    width: 256
verbose: 10
trainer:
    model_dir: '/home/krishnan/models_labelfree/tile256_bs16_mse'
    batch_size: 32
    max_epochs: 10
    metrics: pearson_corr
    loss: mae_loss
    callbacks:
        EarlyStopping:
            mode: min
            monitor: val_pearson_corr
            patience: 1
            verbose: True
        ModelCheckpoint:
            mode: min
            monitor: val_pearson_corr
            save_best_only: True
            verbose: True
        TensorBoard:
            histogram_freq: 0
            verbose: True
    optimizer:
        lr: 0.001
        name: Adam
network:
    class: UNet2D
    num_input_channels: 1
    num_target_channels: 1
    data_format: 'channels_first'
    height: 256
    width: 256
    depth: 1
    batch_norm: True
    pooling_type: average
    filter_size: 3
    activation:
        type: relu
    dropout: 0.2
    dropout_dense: 0.4
    num_filters_per_block: [8, 16, 32, 64, 128]
    num_convs_per_block: 2
    block_sequence: conv-activation-bn
    skip_merge_type: concat
    upsampling: bilinear
    residual: True
    final_activation: linear
